version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gocritic
    - revive
    - misspell

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true

formatters:
  enable:
    - gofmt
